# Kunal Rana

## Batch 3

## TL RAHUL

In [2]:
 import numpy as np

#### Use Numpy to create an array of 20 ‘0s’ and replace the 4th object with the number 5.


In [3]:
array = np.zeros(20)
array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [4]:
array[3] = 4
array

array([0., 0., 0., 4., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

### Perform the following:-
#### Create an array of integers starting from 21 to 30 and name it as ‘Array1’.
#### Create another array of integers from 11 to 20 and name it as ‘Array2’.
#### Calculate the difference between ‘Array1’ and ‘Array2’ and store it in an array named ‘Array3’


In [5]:
Array1 = np.arange(21,30).reshape(3,3)
Array1

array([[21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [6]:
Array2 = np.arange(11,20).reshape(3,3)
Array2

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [7]:
Array3 = Array1 - Array2
Array3

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

### Create a dummy array named as ‘arr’ and find its
#### Length 
#### Dimension
#### Shape
#### Min or Max Element
#### dtype


In [10]:
arr = np.random.randint(1,50,12)
arr

array([18, 42, 32, 37,  4, 33, 13, 21, 27, 15, 26,  4])

In [22]:
print('length of array :', len(arr))
print('Dimension of array :', arr.ndim)
print('Shape of an array :', arr.shape)
print('Min element {} and \nMax elemet {}'.format(arr.min(),arr.max()))
print('Data type of an array is : ', arr.dtype)

length of array : 12
Dimension of array : 1
Shape of an array : (12,)
Min element 4 and 
Max elemet 42
Data type of an array is :  int32


#### Explain with an example how we could convert an array into a matrix. Also find the shape and dimensions of the matrix.


In [29]:
oneD_array = np.random.randint(1,50,12) #it will create one D array
print('one dimension array :', oneD_array)
# BY using .reshape() function we can create one D into matrix 
matrix_ = oneD_array.reshape(3,4)
print('Matrix : \n', matrix_)

one dimension array : [41  1  3 34 10 34  1 24 26 42 33  1]
Matrix : 
 [[41  1  3 34]
 [10 34  1 24]
 [26 42 33  1]]


In [30]:
twoD_array = [[1,2,3],[4,5,6],[7,8,9]]
# By using np.array() we can covert array into matrix
Matrix_ = np.array(twoD_array)
print('Matrix_ :\n', Matrix_)

Matrix_ :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


### Use the matrix in [Q4] to find:-
#### Transpose of the matrix
#### Sum of its elements


In [34]:
print('Orignal matrix :\n', matrix_)

Orignal matrix :
 [[41  1  3 34]
 [10 34  1 24]
 [26 42 33  1]]


In [31]:
print('Transpose of a matrix :\n', matrix_.transpose())

Transpose of the matrix :
 [[41 10 26]
 [ 1 34 42]
 [ 3  1 33]
 [34 24  1]]


In [33]:
print('Sum of a matrix :\n', matrix_.sum())

Sum of a matrix :
 250


#### Create an identity matrix of shape (10X10) and replace the 0’s with ‘21

In [36]:
identity_matrix = np.eye(10,10)
print('Identity matrix : \n', identity_matrix)

Identity matrix : 
 [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [37]:
identity_matrix[identity_matrix==0] = 21
print(identity_matrix)

[[ 1. 21. 21. 21. 21. 21. 21. 21. 21. 21.]
 [21.  1. 21. 21. 21. 21. 21. 21. 21. 21.]
 [21. 21.  1. 21. 21. 21. 21. 21. 21. 21.]
 [21. 21. 21.  1. 21. 21. 21. 21. 21. 21.]
 [21. 21. 21. 21.  1. 21. 21. 21. 21. 21.]
 [21. 21. 21. 21. 21.  1. 21. 21. 21. 21.]
 [21. 21. 21. 21. 21. 21.  1. 21. 21. 21.]
 [21. 21. 21. 21. 21. 21. 21.  1. 21. 21.]
 [21. 21. 21. 21. 21. 21. 21. 21.  1. 21.]
 [21. 21. 21. 21. 21. 21. 21. 21. 21.  1.]]


#### Use the given sample matrix to perform the following operations in an array:- 
#### array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
####      [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
####      [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
####      [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
####      [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
####      [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
####      [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
####      [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
####      [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
####      [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])


In [38]:
samplematrix = np.array(([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],[ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],[ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],[ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],[ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],[ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],[ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],[ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],[ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],[ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]))
print(samplematrix)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [41]:
#####Retrieve the last 2 rows and first 3 column values of the above matrix.
print(samplematrix[-2:,:3])

[[81 82 83]
 [91 92 93]]


In [42]:
######Retrieve the value 55 from the above matrix.
samplematrix[5,4]

55

In [43]:
#####Retrieve values from the 3rd column in the above matrix.
column3 = samplematrix[:, 3]
column3

array([ 4, 14, 24, 34, 44, 54, 64, 74, 84, 94])

In [44]:
#####Retrieve values from the 6th row in the above matrix.
row6 = samplematrix[5]
row6

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60])

In [45]:
######Calculate the mean and variance of sum of all the values in the matrix.
print('Mean = ', samplematrix.mean() )
print('Variance = ', np.var(samplematrix))

Mean =  50.5
Variance =  833.25


In [47]:
######Retrieve the largest number from the matrix.
print('Maximum Value in matrix is = ', samplematrix.max())

Maximum Value in matrix is =  100


#### Display all even numbers between 0 to 40, with a stop value of 4.

In [48]:
evenvalue = np.arange(0,41,4)
evenvalue

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40])

### Explain the difference between 
#### ‘rand’ and ‘randn’ with a suitable example.
#### ‘argmin’/’argmax’ and ‘min’/’max’ with a suitable example.


In [49]:
# rand returns array with random variables from "uniform distribution"
np.random.rand(5)

array([0.94207041, 0.40066069, 0.06319117, 0.3844038 , 0.99270927])

In [50]:
#randn returns array with random variables from "Standard distribution"
#i.e mean as 0 and standard deviation of 1
np.random.randn(5)

array([ 0.42363703, -1.22963261,  1.57794994, -1.25168822, -0.5833843 ])

In [52]:
# while min/max return minimun or maximum value in the array, 
#argmin/argmax returns the index location of the minimum or maximum value

#using random array
array = np.random.randint(0,100,20)
print('array',array)
print('\nMinimum value = ', array.min(),'\nMaximum value = ',array.max())# returns min and max values

print('\nArgmin = ', array.argmin(),'\nArgmax = ', array.argmax())#returns indeces of min and max values


array [31 66 36 46 50 77 21  4 62 94 58 46 81 87 47  0 84 18 13 16]

Minimum value =  0 
Maximum value =  94

Argmin =  15 
Argmax =  9


#### Create a random (6X2) array and reshape it as (2X6).

In [54]:
random_matrix = np.random.rand(6,2)
random_matrix

array([[0.84656417, 0.49372119],
       [0.50543095, 0.03743238],
       [0.18367422, 0.44414986],
       [0.60296732, 0.17688752],
       [0.55692204, 0.16596346],
       [0.98396166, 0.5745127 ]])

In [55]:
random_matrix.reshape(2,6)

array([[0.84656417, 0.49372119, 0.50543095, 0.03743238, 0.18367422,
        0.44414986],
       [0.60296732, 0.17688752, 0.55692204, 0.16596346, 0.98396166,
        0.5745127 ]])

#### Give a valid point of difference between ‘linspace’ and ‘arange’ functions.

In [56]:
# linspace returns evenly spaced numbers 'over' a specified interval and last number is included.
# linspace allows you to define number of steps

np.linspace(0,30,4) # this gives 4 evenly spaced numbers from 0 to 30,inluding 30


array([ 0., 10., 20., 30.])

In [57]:
# arange returns evenly spaced values 'within' a given interval.
# arange allows you to define the size of the step

np.arange(0,30, 4) #however many are needed from 0 to 30 with an interval of 4, excluding 30

array([ 0,  4,  8, 12, 16, 20, 24, 28])

### Use your array in [Q3] to find the values of 
#### arr[-2:]
#### arr[0:3]
#### arr[-4]


In [58]:
arr[-2:]

array([26,  4])

In [59]:
arr[0:3]

array([18, 42, 32])

In [60]:
arr[-4]

27

###### Create an array named ‘simple_array’ with values starting from 1 to 31. Apply a condition over it as a simple_array <10 and name the resultant array as ‘boolean_array’ and display it.


In [61]:
simple_array = np.arange(1,32)
boolean_array = simple_array<10
boolean_array

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False])

### Quote suitable examples to showcase the usage of the following functions in Numpy:-


In [62]:
# .log() gives the Natural Logarithm (log) of the Input value, element-wise.
example_array = ([10,20,30,40,50]) #example array

np.log(example_array) #returns log of all values

array([2.30258509, 2.99573227, 3.40119738, 3.68887945, 3.91202301])

In [63]:
# .rounds() rounds of the value to given decimal points, takes parameter "decimals"
log = np.log(example_array)
np.round(log, decimals=2) #log from previous cell

array([2.3 , 3.  , 3.4 , 3.69, 3.91])

In [64]:
# .sqrt() returns the square root
np.sqrt(example_array)

array([3.16227766, 4.47213595, 5.47722558, 6.32455532, 7.07106781])

In [65]:
# .exp() return the epontential values (e^)
np.exp(example_array)

array([2.20264658e+04, 4.85165195e+08, 1.06864746e+13, 2.35385267e+17,
       5.18470553e+21])